apiVersion: v1
kind: Service
metadata:
  name: springbootdocker-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: springbootdocker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
